name: Auditorium
favicon: null
layout_spectrum: 0.25058
typography_spectrum: 0.2354598029050976
title: Auditorium
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4e4da'
    - '#000000'
    - '#dcd8cd'
    - '#d4d0c7'
    - '#cac3bc'
  brandStrength: 0.5457471662666649
  lightness: 0.8624427889008075
  saturation: 0.979693230940029
  rhythmicContrast: 0.05790942767634988
purpose: []
