name: Auditorium
favicon: null
layout_spectrum: 0.25058
typography_spectrum: 1
title: Auditorium
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4e4da'
    - '#000000'
    - '#dcd8cd'
    - '#d4d0c7'
    - '#cac3bc'
  brandStrength: 0.6875
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
